naming:
  entity: "shd"
  workload: "shaks"
  environment: "dev"
  region: "euw"
  cf_code: "yjjlh" #should be change later (room for improvement)

mgmt:
  acr_random_string: ""
  amg_random_string: ""
  environment: "mgt"
  ado_principal_id: ""

aks:
  location: "westeurope"
  aks_version: "1.33"
  aks_sku_tier: "Premium"
  pim_enabled: true
  pim_justification: "Admin access to AKS cluster"
  enable_backup: true
  appgw_private_ip_address: ""
  availability_zones: [1, 2, 3]
  aks_number_of_node_pools: 1
  aks_nodepools_config:
    pool001:
      name: "pool001"
      vm_size: "Standard_d8ds_v6"
      min_count: 1
      max_count: 5
      enable_auto_scaling: true
      enable_host_encryption: true
      max_pods: 50
      os_disk_type: "Managed"
      scale_down_mode: "Deallocate"
  aks_system_nodes_config:
    vm_size: "Standard_d4ds_v6"
    min_count: 1
    max_count: 5
    enable_auto_scaling: true
    enable_host_encryption: true
    max_pods: 50
    only_critical_addons_enabled: true
    os_disk_type: "Managed"
    scale_down_mode: "Deallocate"
